/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dark-minaz (https://sketchfab.com/dark-minaz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floating-space-rocks-018829759661494080f08368bb742ca4
Title: Floating Space Rocks
*/

import { useGLTF } from '@react-three/drei'
import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';

const World = (props) => {
  const { nodes, materials } = useGLTF('/models/floating_space_rocks.glb')
  const groupRef = useRef();

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.01;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null} scale={[0.01, 0.01, 0.01]} position={[3.5, -4, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Sphere}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Rocks}
          scale={2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Rocks}
          scale={2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Rocks}
          scale={2}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/floating_space_rocks.glb')
export default World;